name: retorki_feladatkezelo_02
description: "RETÖRKI Feladatkezelő 0.2 - Egy webes alapú feladatkezelő alkalmazás."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.8
  js: ^0.7.1
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_localizations: # Hozzáadjuk a lokalizációs csomagot
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png