// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeMjVqmkdzPWf-GUxYTLr6Aavk0L9je6Q',
    appId: '1:68614643701:web:0da2bd5b180e978c124abc',
    messagingSenderId: '68614643701',
    projectId: 'retorki-feladatkezelo-02',
    authDomain: 'retorki-feladatkezelo-02.firebaseapp.com',
    storageBucket: 'retorki-feladatkezelo-02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFhCPIlodUC8cGdJK4ZWK81tGyJqhxiXA',
    appId: '1:68614643701:android:2a5bf2cfbdd486a3124abc',
    messagingSenderId: '68614643701',
    projectId: 'retorki-feladatkezelo-02',
    storageBucket: 'retorki-feladatkezelo-02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7ANSQzRprcXWBuiCpLlAt5jexTf8SkE',
    appId: '1:68614643701:ios:193fbd91a0250381124abc',
    messagingSenderId: '68614643701',
    projectId: 'retorki-feladatkezelo-02',
    storageBucket: 'retorki-feladatkezelo-02.firebasestorage.app',
    iosBundleId: 'com.example.retorkiFeladatkezelo02',
  );
}
